package io.github.jaloon.jsqlparser.test.visitor

import io.github.jaloon.jsqlparser.SqlContext
import net.sf.jsqlparser.expression.*
import net.sf.jsqlparser.expression.Function
import net.sf.jsqlparser.expression.operators.arithmetic.*
import net.sf.jsqlparser.expression.operators.conditional.AndExpression
import net.sf.jsqlparser.expression.operators.conditional.OrExpression
import net.sf.jsqlparser.expression.operators.conditional.XorExpression
import net.sf.jsqlparser.expression.operators.relational.*
import net.sf.jsqlparser.schema.Column
import net.sf.jsqlparser.statement.piped.FromQuery
import net.sf.jsqlparser.statement.select.AllColumns
import net.sf.jsqlparser.statement.select.AllTableColumns
import net.sf.jsqlparser.statement.select.FunctionAllColumns
import net.sf.jsqlparser.statement.select.ParenthesedSelect
import net.sf.jsqlparser.statement.select.Select

/**
 * @see ExpressionVisitor
 */
interface ExpressionContextVisitor {
    fun visit(bitwiseRightShift: BitwiseRightShift?, context: SqlContext)
    fun visit(bitwiseLeftShift: BitwiseLeftShift?, context: SqlContext)
    fun visit(nullValue: NullValue?, context: SqlContext)
    fun visit(function: Function?, context: SqlContext)
    fun visit(signedExpression: SignedExpression?, context: SqlContext)
    fun visit(jdbcParameter: JdbcParameter?, context: SqlContext)
    fun visit(jdbcNamedParameter: JdbcNamedParameter?, context: SqlContext)
    fun visit(doubleValue: DoubleValue?, context: SqlContext)
    fun visit(longValue: LongValue?, context: SqlContext)
    fun visit(hexValue: HexValue?, context: SqlContext)
    fun visit(dateValue: DateValue?, context: SqlContext)
    fun visit(timeValue: TimeValue?, context: SqlContext)
    fun visit(timestampValue: TimestampValue?, context: SqlContext)
    fun visit(stringValue: StringValue?, context: SqlContext)
    fun visit(booleanValue: BooleanValue?, context: SqlContext)
    fun visit(addition: Addition?, context: SqlContext)
    fun visit(division: Division?, context: SqlContext)
    fun visit(integerDivision: IntegerDivision?, context: SqlContext)
    fun visit(multiplication: Multiplication?, context: SqlContext)
    fun visit(subtraction: Subtraction?, context: SqlContext)
    fun visit(andExpression: AndExpression?, context: SqlContext)
    fun visit(orExpression: OrExpression?, context: SqlContext)
    fun visit(xorExpression: XorExpression?, context: SqlContext)
    fun visit(between: Between?, context: SqlContext)
    fun visit(overlapsCondition: OverlapsCondition?, context: SqlContext)
    fun visit(equalsTo: EqualsTo?, context: SqlContext)
    fun visit(greaterThan: GreaterThan?, context: SqlContext)
    fun visit(greaterThanEquals: GreaterThanEquals?, context: SqlContext)
    fun visit(inExpression: InExpression?, context: SqlContext)
    fun visit(includesExpression: IncludesExpression?, context: SqlContext)
    fun visit(excludesExpression: ExcludesExpression?, context: SqlContext)
    fun visit(fullTextSearch: FullTextSearch?, context: SqlContext)
    fun visit(isNullExpression: IsNullExpression?, context: SqlContext)
    fun visit(isBooleanExpression: IsBooleanExpression?, context: SqlContext)
    fun visit(isUnknownExpression: IsUnknownExpression?, context: SqlContext)
    fun visit(likeExpression: LikeExpression?, context: SqlContext)
    fun visit(minorThan: MinorThan?, context: SqlContext)
    fun visit(minorThanEquals: MinorThanEquals?, context: SqlContext)
    fun visit(notEqualsTo: NotEqualsTo?, context: SqlContext)
    fun visit(doubleAnd: DoubleAnd?, context: SqlContext)
    fun visit(contains: Contains?, context: SqlContext)
    fun visit(containedBy: ContainedBy?, context: SqlContext)
    fun visit(select: ParenthesedSelect?, context: SqlContext)
    fun visit(column: Column?, context: SqlContext)
    fun visit(caseExpression: CaseExpression?, context: SqlContext)
    fun visit(whenClause: WhenClause?, context: SqlContext)
    fun visit(existsExpression: ExistsExpression?, context: SqlContext)
    fun visit(memberOfExpression: MemberOfExpression?, context: SqlContext)
    fun visit(anyComparisonExpression: AnyComparisonExpression?, context: SqlContext)
    fun visit(concat: Concat?, context: SqlContext)
    fun visit(matches: Matches?, context: SqlContext)
    fun visit(bitwiseAnd: BitwiseAnd?, context: SqlContext)
    fun visit(bitwiseOr: BitwiseOr?, context: SqlContext)
    fun visit(bitwiseXor: BitwiseXor?, context: SqlContext)
    fun visit(castExpression: CastExpression?, context: SqlContext)
    fun visit(modulo: Modulo?, context: SqlContext)
    fun visit(analyticExpression: AnalyticExpression?, context: SqlContext)
    fun visit(extractExpression: ExtractExpression?, context: SqlContext)
    fun visit(intervalExpression: IntervalExpression?, context: SqlContext)
    fun visit(hierarchicalExpression: OracleHierarchicalExpression?, context: SqlContext)
    fun visit(regExpMatchOperator: RegExpMatchOperator?, context: SqlContext)
    fun visit(jsonExpression: JsonExpression?, context: SqlContext)
    fun visit(jsonOperator: JsonOperator?, context: SqlContext)
    fun visit(userVariable: UserVariable?, context: SqlContext)
    fun visit(numericBind: NumericBind?, context: SqlContext)
    fun visit(keepExpression: KeepExpression?, context: SqlContext)
    fun visit(groupConcat: MySQLGroupConcat?, context: SqlContext)
    fun visit(expressionList: ExpressionList<out Expression?>?, context: SqlContext)
    fun visit(rowConstructor: RowConstructor<out Expression?>?, context: SqlContext)
    fun visit(rowGetExpression: RowGetExpression?, context: SqlContext)
    fun visit(hint: OracleHint?, context: SqlContext)
    fun visit(timeKeyExpression: TimeKeyExpression?, context: SqlContext)
    fun visit(dateTimeLiteralExpression: DateTimeLiteralExpression?, context: SqlContext)
    fun visit(notExpression: NotExpression?, context: SqlContext)
    fun visit(nextValExpression: NextValExpression?, context: SqlContext)
    fun visit(collateExpression: CollateExpression?, context: SqlContext)
    fun visit(similarToExpression: SimilarToExpression?, context: SqlContext)
    fun visit(arrayExpression: ArrayExpression?, context: SqlContext)
    fun visit(arrayConstructor: ArrayConstructor?, context: SqlContext)
    fun visit(variableAssignment: VariableAssignment?, context: SqlContext)
    fun visit(xmlSerializeExpr: XMLSerializeExpr?, context: SqlContext)
    fun visit(timezoneExpression: TimezoneExpression?, context: SqlContext)
    fun visit(jsonAggregateFunction: JsonAggregateFunction?, context: SqlContext)
    fun visit(jsonFunction: JsonFunction?, context: SqlContext)
    fun visit(connectByRootOperator: ConnectByRootOperator?, context: SqlContext)
    fun visit(connectByPriorOperator: ConnectByPriorOperator?, context: SqlContext)
    fun visit(oracleNamedFunctionParameter: OracleNamedFunctionParameter?, context: SqlContext)
    fun visit(allColumns: AllColumns?, context: SqlContext)
    fun visit(functionColumns: FunctionAllColumns?, context: SqlContext)
    fun visit(allTableColumns: AllTableColumns?, context: SqlContext)
    fun visit(allValue: AllValue?, context: SqlContext)
    fun visit(isDistinctExpression: IsDistinctExpression?, context: SqlContext)
    fun visit(geometryDistance: GeometryDistance?, context: SqlContext)
    fun visit(select: Select?, context: SqlContext)
    fun visit(transcodingFunction: TranscodingFunction?, context: SqlContext)
    fun visit(trimFunction: TrimFunction?, context: SqlContext)
    fun visit(rangeExpression: RangeExpression?, context: SqlContext)
    fun visit(tsqlLeftJoin: TSQLLeftJoin?, context: SqlContext)
    fun visit(tsqlRightJoin: TSQLRightJoin?, context: SqlContext)
    fun visit(structType: StructType?, context: SqlContext)
    fun visit(lambdaExpression: LambdaExpression?, context: SqlContext)
    fun visit(highExpression: HighExpression?, context: SqlContext)
    fun visit(lowExpression: LowExpression?, context: SqlContext)
    fun visit(plus: Plus?, context: SqlContext)
    fun visit(priorTo: PriorTo?, context: SqlContext)
    fun visit(inverse: Inverse?, context: SqlContext)
    fun visit(cosineSimilarity: CosineSimilarity?, context: SqlContext)
    fun visit(fromQuery: FromQuery?, context: SqlContext)
}